# Generated by Django 4.2.11 on 2024-04-03 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupName', models.CharField(default='allProduict', max_length=100)),
                ('imageGrup', models.ImageField(default='static/def.jpg', upload_to='')),
                ('authAddImage', models.TextField(blank=True)),
                ('your_boolean_field', models.BooleanField(default=False)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_boolean_field', models.BooleanField(default=False)),
                ('productName', models.CharField(max_length=100)),
                ('priceProduct', models.IntegerField(default=0)),
                ('totalProduct', models.IntegerField(default=0)),
                ('imageProduct', models.ImageField(default='static/def.jpg', upload_to='your_directory/')),
                ('authAddImage', models.TextField(blank=True)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='audit.grupproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMoney', models.IntegerField(blank=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='audit.grupproduct')),
            ],
        ),
    ]
